[package]
name = "abvt"
version = "0.1.0"
authors = ["harshad deo"]
edition = "2018"

[dependencies]
flatbuffers = "0.6.1"
futures = "0.3.5"
log = "0.4"
pretty_env_logger = "0.4.0"
tokio = { version = "0.2.21", features = ["full"] }
warp = "0.2.3"